import TAccount from '@/types/account';
import TBank from '@/types/bank';
import TCreditCard from '@/types/credit-card';
import TTransaction from '@/types/transaction';
import { TUser } from '@/types/user';

const USER: TUser = {
  id: '1',
  email: 'example@gmail.com',
  firstName: 'John',
  lastName: 'Doe',
  image: '/avatar.webp',
};
const ACCOUNTS: TAccount[] = [
  {
    id: 'acc1',
    availableBalance: 1500.75,
    currentBalance: 1600.0,
    officialName: 'Primary Checking Account',
    mask: '1234',
    institutionId: 'inst1',
    name: 'John Doe Checking',
    type: 'depository',
    subtype: 'checking',
    appwriteItemId: 'item1',
    shareableId: 'share1',
    color: 'blue',
  },
  {
    id: 'acc2',
    availableBalance: 5000.0,
    currentBalance: 5000.0,
    officialName: 'High-Yield Savings Account',
    mask: '5678',
    institutionId: 'inst2',
    name: 'John Doe Savings',
    type: 'depository',
    subtype: 'savings',
    appwriteItemId: 'item2',
    shareableId: 'share2',
    color: 'green',
  },
  {
    id: 'acc3',
    availableBalance: 200.0,
    currentBalance: 1200.0,
    officialName: 'Visa Credit Card',
    mask: '9876',
    institutionId: 'inst3',
    name: 'John Doe Visa',
    type: 'credit',
    subtype: 'credit card',
    appwriteItemId: 'item3',
    shareableId: 'share3',
    color: 'red',
  },
  {
    id: 'acc4',
    availableBalance: 0.0,
    currentBalance: 15000.0,
    officialName: 'Car Loan',
    mask: '4321',
    institutionId: 'inst4',
    name: 'John Doe Auto Loan',
    type: 'loan',
    subtype: 'auto',
    appwriteItemId: 'item4',
    shareableId: 'share4',
    color: 'yellow',
  },
  {
    id: 'acc5',
    availableBalance: 2500.0,
    currentBalance: 2500.0,
    officialName: 'Personal Investment Account',
    mask: '1122',
    institutionId: 'inst5',
    name: 'John Doe Investments',
    type: 'investment',
    subtype: 'investment',
    appwriteItemId: 'item5',
    shareableId: 'share5',
    color: 'purple',
  },
  {
    id: 'acc6',
    availableBalance: 300.0,
    currentBalance: 1300.0,
    officialName: 'MasterCard Credit Card',
    mask: '3344',
    institutionId: 'inst6',
    name: 'John Doe MasterCard',
    type: 'credit',
    subtype: 'credit card',
    appwriteItemId: 'item6',
    shareableId: 'share6',
    color: 'pink',
  },
  {
    id: 'acc7',
    availableBalance: 1000.0,
    currentBalance: 2000.0,
    officialName: 'Line of Credit',
    mask: '5566',
    institutionId: 'inst7',
    name: 'John Doe Line of Credit',
    type: 'loan',
    subtype: 'line of credit',
    appwriteItemId: 'item7',
    shareableId: 'share7',
    color: 'indigo',
  },
  {
    id: 'acc8',
    availableBalance: 4000.0,
    currentBalance: 4000.0,
    officialName: 'Emergency Savings Account',
    mask: '7788',
    institutionId: 'inst8',
    name: 'John Doe Emergency Savings',
    type: 'depository',
    subtype: 'savings',
    appwriteItemId: 'item8',
    shareableId: 'share8',
    color: 'cyan',
  },
  {
    id: 'acc9',
    availableBalance: 0.0,
    currentBalance: 20000.0,
    officialName: 'Student Loan',
    mask: '9900',
    institutionId: 'inst9',
    name: 'John Doe Student Loan',
    type: 'loan',
    subtype: 'student',
    appwriteItemId: 'item9',
    shareableId: 'share9',
    color: 'teal',
  },
  {
    id: 'acc10',
    availableBalance: 50.0,
    currentBalance: 150.0,
    officialName: 'Other Account',
    mask: '4455',
    institutionId: 'inst10',
    name: 'John Doe Miscellaneous',
    type: 'other',
    subtype: 'other',
    appwriteItemId: 'item10',
    shareableId: 'share10',
    color: 'gray',
  },
];
const BANKS: TBank[] = [
  {
    $id: 'bank1',
    accountId: 'acc1',
    bankId: 'inst1',
    accessToken: 'token1',
    fundingSourceUrl: 'https://bank1.com/fundingsource1',
    userId: 'user1',
    shareableId: 'share1',
  },
  {
    $id: 'bank2',
    accountId: 'acc2',
    bankId: 'inst2',
    accessToken: 'token2',
    fundingSourceUrl: 'https://bank2.com/fundingsource2',
    userId: 'user2',
    shareableId: 'share2',
  },
  {
    $id: 'bank3',
    accountId: 'acc3',
    bankId: 'inst3',
    accessToken: 'token3',
    fundingSourceUrl: 'https://bank3.com/fundingsource3',
    userId: 'user3',
    shareableId: 'share3',
  },
  {
    $id: 'bank4',
    accountId: 'acc4',
    bankId: 'inst4',
    accessToken: 'token4',
    fundingSourceUrl: 'https://bank4.com/fundingsource4',
    userId: 'user4',
    shareableId: 'share4',
  },
  {
    $id: 'bank5',
    accountId: 'acc5',
    bankId: 'inst5',
    accessToken: 'token5',
    fundingSourceUrl: 'https://bank5.com/fundingsource5',
    userId: 'user5',
    shareableId: 'share5',
  },
  {
    $id: 'bank6',
    accountId: 'acc6',
    bankId: 'inst6',
    accessToken: 'token6',
    fundingSourceUrl: 'https://bank6.com/fundingsource6',
    userId: 'user6',
    shareableId: 'share6',
  },
  {
    $id: 'bank7',
    accountId: 'acc7',
    bankId: 'inst7',
    accessToken: 'token7',
    fundingSourceUrl: 'https://bank7.com/fundingsource7',
    userId: 'user7',
    shareableId: 'share7',
  },
  {
    $id: 'bank8',
    accountId: 'acc8',
    bankId: 'inst8',
    accessToken: 'token8',
    fundingSourceUrl: 'https://bank8.com/fundingsource8',
    userId: 'user8',
    shareableId: 'share8',
  },
  {
    $id: 'bank9',
    accountId: 'acc9',
    bankId: 'inst9',
    accessToken: 'token9',
    fundingSourceUrl: 'https://bank9.com/fundingsource9',
    userId: 'user9',
    shareableId: 'share9',
  },
  {
    $id: 'bank10',
    accountId: 'acc10',
    bankId: 'inst10',
    accessToken: 'token10',
    fundingSourceUrl: 'https://bank10.com/fundingsource10',
    userId: 'user10',
    shareableId: 'share10',
  },
];
const TRANSACTIONS: TTransaction[] = [
  {
    id: 'tx1',
    $id: 'txid1',
    name: 'Grocery Store',
    paymentChannel: 'online',
    accountId: 'acc1',
    amount: 75.23,
    pending: false,
    status: 'Success',
    category: 'Groceries',
    date: '2024-06-01',
    image: 'https://example.com/images/tx1.jpg',
    type: 'Debit',
    $createdAt: '2024-06-01T10:00:00Z',
    channel: 'Online',
    senderBankId: 'bank1',
    receiverBankId: 'bank2',
  },
  {
    id: 'tx2',
    $id: 'txid2',
    name: 'Restaurant',
    paymentChannel: 'in-store',
    accountId: 'acc1',
    amount: 45.67,
    pending: false,
    status: 'Processing',
    category: 'Food and Drink',
    date: '2024-06-02',
    image: 'https://example.com/images/tx2.jpg',
    type: 'Debit',
    $createdAt: '2024-06-02T12:30:00Z',
    channel: 'In-Store',
    senderBankId: 'bank1',
    receiverBankId: 'bank3',
  },
  {
    id: 'tx3',
    $id: 'txid3',
    name: 'Salary Payment',
    paymentChannel: 'direct deposit',
    accountId: 'acc1',
    amount: 1500.0,
    pending: false,
    status: 'Success',
    category: 'Salary',
    date: '2024-06-03',
    image: 'https://example.com/images/tx3.jpg',
    type: 'Credit',
    $createdAt: '2024-06-03T08:00:00Z',
    channel: 'Direct Deposit',
    senderBankId: 'bank4',
    receiverBankId: 'bank1',
  },
  {
    id: 'tx4',
    $id: 'txid4',
    name: 'Electricity Bill',
    paymentChannel: 'online',
    accountId: 'acc1',
    amount: 120.45,
    pending: false,
    status: 'Declined',
    category: 'Utilities',
    date: '2024-06-04',
    image: 'https://example.com/images/tx4.jpg',
    type: 'Debit',
    $createdAt: '2024-06-04T09:00:00Z',
    channel: 'Online',
    senderBankId: 'bank1',
    receiverBankId: 'bank5',
  },
  {
    id: 'tx5',
    $id: 'txid5',
    name: 'Rent Payment',
    paymentChannel: 'online',
    accountId: 'acc1',
    amount: 800.0,
    pending: false,
    status: 'Success',
    category: 'Housing',
    date: '2024-06-05',
    image: 'https://example.com/images/tx5.jpg',
    type: 'Debit',
    $createdAt: '2024-06-05T10:00:00Z',
    channel: 'Online',
    senderBankId: 'bank1',
    receiverBankId: 'bank6',
  },
  {
    id: 'tx6',
    $id: 'txid6',
    name: 'Amazon Purchase',
    paymentChannel: 'online',
    accountId: 'acc1',
    amount: 56.78,
    pending: false,
    status: 'Success',
    category: 'Shopping',
    date: '2024-06-06',
    image: 'https://example.com/images/tx6.jpg',
    type: 'Debit',
    $createdAt: '2024-06-06T11:00:00Z',
    channel: 'Online',
    senderBankId: 'bank1',
    receiverBankId: 'bank7',
  },
  {
    id: 'tx7',
    $id: 'txid7',
    name: 'Spotify Subscription',
    paymentChannel: 'online',
    accountId: 'acc1',
    amount: 9.99,
    pending: false,
    status: 'Success',
    category: 'Subscription',
    date: '2024-06-07',
    image: 'https://example.com/images/tx7.jpg',
    type: 'Debit',
    $createdAt: '2024-06-07T12:00:00Z',
    channel: 'Online',
    senderBankId: 'bank1',
    receiverBankId: 'bank8',
  },
  {
    id: 'tx8',
    $id: 'txid8',
    name: 'ATM Withdrawal',
    paymentChannel: 'ATM',
    accountId: 'acc1',
    amount: 200.0,
    pending: false,
    status: 'Success',
    category: 'Withdrawal',
    date: '2024-06-08',
    image: 'https://example.com/images/tx8.jpg',
    type: 'Debit',
    $createdAt: '2024-06-08T13:00:00Z',
    channel: 'ATM',
    senderBankId: 'bank1',
    receiverBankId: 'bank9',
  },
  {
    id: 'tx9',
    $id: 'txid9',
    name: 'Transfer to Savings',
    paymentChannel: 'online',
    accountId: 'acc1',
    amount: 300.0,
    pending: false,
    status: 'Success',
    category: 'Transfer',
    date: '2024-06-09',
    image: 'https://example.com/images/tx9.jpg',
    type: 'Debit',
    $createdAt: '2024-06-09T14:00:00Z',
    channel: 'Online',
    senderBankId: 'bank1',
    receiverBankId: 'bank10',
  },
  {
    id: 'tx10',
    $id: 'txid10',
    name: 'Deposit from PayPal',
    paymentChannel: 'online',
    accountId: 'acc1',
    amount: 250.0,
    pending: false,
    status: 'Success',
    category: 'Deposit',
    date: '2024-06-10',
    image: 'https://example.com/images/tx10.jpg',
    type: 'Credit',
    $createdAt: '2024-06-10T15:00:00Z',
    channel: 'Online',
    senderBankId: 'bank11',
    receiverBankId: 'bank1',
  },
  {
    id: 'tx11',
    $id: 'txid11',
    name: 'Uber Ride',
    paymentChannel: 'online',
    accountId: 'acc2',
    amount: 15.6,
    pending: false,
    status: 'Success',
    category: 'Travel',
    date: '2024-06-11',
    image: 'https://example.com/images/tx11.jpg',
    type: 'Debit',
    $createdAt: '2024-06-11T16:00:00Z',
    channel: 'Online',
    senderBankId: 'bank2',
    receiverBankId: 'bank12',
  },
  {
    id: 'tx12',
    $id: 'txid12',
    name: 'Gym Membership',
    paymentChannel: 'online',
    accountId: 'acc2',
    amount: 30.0,
    pending: false,
    status: 'Success',
    category: 'Subscription',
    date: '2024-06-12',
    image: 'https://example.com/images/tx12.jpg',
    type: 'Debit',
    $createdAt: '2024-06-12T17:00:00Z',
    channel: 'Online',
    senderBankId: 'bank2',
    receiverBankId: 'bank13',
  },
  {
    id: 'tx13',
    $id: 'txid13',
    name: 'Stock Purchase',
    paymentChannel: 'online',
    accountId: 'acc2',
    amount: 500.0,
    pending: false,
    status: 'Success',
    category: 'Investment',
    date: '2024-06-13',
    image: 'https://example.com/images/tx13.jpg',
    type: 'Debit',
    $createdAt: '2024-06-13T18:00:00Z',
    channel: 'Online',
    senderBankId: 'bank2',
    receiverBankId: 'bank14',
  },
  {
    id: 'tx14',
    $id: 'txid14',
    name: 'Coffee Shop',
    paymentChannel: 'in-store',
    accountId: 'acc2',
    amount: 5.45,
    pending: false,
    status: 'Success',
    category: 'Food',
    date: '2024-06-14',
    image: 'https://example.com/images/tx14.jpg',
    type: 'Debit',
    $createdAt: '2024-06-14T19:00:00Z',
    channel: 'In-Store',
    senderBankId: 'bank2',
    receiverBankId: 'bank15',
  },
  {
    id: 'tx15',
    $id: 'txid15',
    name: 'Monthly Rent',
    paymentChannel: 'online',
    accountId: 'acc2',
    amount: 800.0,
    pending: false,
    status: 'Success',
    category: 'Rent',
    date: '2024-06-15',
    image: 'https://example.com/images/tx15.jpg',
    type: 'Debit',
    $createdAt: '2024-06-15T20:00:00Z',
    channel: 'Online',
    senderBankId: 'bank2',
    receiverBankId: 'bank6',
  },
  {
    id: 'tx16',
    $id: 'txid16',
    name: 'Interest Income',
    paymentChannel: 'direct deposit',
    accountId: 'acc3',
    amount: 10.5,
    pending: false,
    status: 'Success',
    category: 'Interest',
    date: '2024-06-16',
    image: 'https://example.com/images/tx16.jpg',
    type: 'Credit',
    $createdAt: '2024-06-16T21:00:00Z',
    channel: 'Direct Deposit',
    senderBankId: 'bank16',
    receiverBankId: 'bank3',
  },
  {
    id: 'tx17',
    $id: 'txid17',
    name: 'Credit Card Payment',
    paymentChannel: 'online',
    accountId: 'acc3',
    amount: 200.0,
    pending: false,
    status: 'Success',
    category: 'Credit Card',
    date: '2024-06-17',
    image: 'https://example.com/images/tx17.jpg',
    type: 'Debit',
    $createdAt: '2024-06-17T22:00:00Z',
    channel: 'Online',
    senderBankId: 'bank3',
    receiverBankId: 'bank5',
  },
  {
    id: 'tx18',
    $id: 'txid18',
    name: 'Loan Repayment',
    paymentChannel: 'online',
    accountId: 'acc3',
    amount: 300.0,
    pending: false,
    status: 'Success',
    category: 'Loan',
    date: '2024-06-18',
    image: 'https://example.com/images/tx18.jpg',
    type: 'Debit',
    $createdAt: '2024-06-18T23:00:00Z',
    channel: 'Online',
    senderBankId: 'bank3',
    receiverBankId: 'bank7',
  },
  {
    id: 'tx19',
    $id: 'txid19',
    name: 'Freelance Income',
    paymentChannel: 'online',
    accountId: 'acc3',
    amount: 1000.0,
    pending: false,
    status: 'Success',
    category: 'Income',
    date: '2024-06-19',
    image: 'https://example.com/images/tx19.jpg',
    type: 'Credit',
    $createdAt: '2024-06-19T09:00:00Z',
    channel: 'Online',
    senderBankId: 'bank8',
    receiverBankId: 'bank3',
  },
  {
    id: 'tx20',
    $id: 'txid20',
    name: 'Miscellaneous Expense',
    paymentChannel: 'in-store',
    accountId: 'acc3',
    amount: 25.0,
    pending: false,
    status: 'Success',
    category: 'Other',
    date: '2024-06-20',
    image: 'https://example.com/images/tx20.jpg',
    type: 'Debit',
    $createdAt: '2024-06-20T10:00:00Z',
    channel: 'In-Store',
    senderBankId: 'bank3',
    receiverBankId: 'bank9',
  },

  {
    id: 'tx21',
    $id: 'txid21',
    name: 'Supermarket',
    paymentChannel: 'in-store',
    accountId: 'acc1',
    amount: 87.32,
    pending: false,
    status: 'Success',
    category: 'Groceries',
    date: '2024-06-21',
    image: 'https://example.com/images/tx21.jpg',
    type: 'Debit',
    $createdAt: '2024-06-21T10:15:00Z',
    channel: 'In-Store',
    senderBankId: 'bank1',
    receiverBankId: 'bank11',
  },
  {
    id: 'tx22',
    $id: 'txid22',
    name: 'Gas Station',
    paymentChannel: 'in-store',
    accountId: 'acc1',
    amount: 45.0,
    pending: false,
    status: 'Processing',
    category: 'Transfer',
    date: '2024-06-22',
    image: 'https://example.com/images/tx22.jpg',
    type: 'Debit',
    $createdAt: '2024-06-22T14:30:00Z',
    channel: 'In-Store',
    senderBankId: 'bank1',
    receiverBankId: 'bank12',
  },
  {
    id: 'tx23',
    $id: 'txid23',
    name: 'Online Course Subscription',
    paymentChannel: 'online',
    accountId: 'acc2',
    amount: 199.99,
    pending: false,
    status: 'Declined',
    category: 'Investment',
    date: '2024-06-23',
    image: 'https://example.com/images/tx23.jpg',
    type: 'Debit',
    $createdAt: '2024-06-23T09:45:00Z',
    channel: 'Online',
    senderBankId: 'bank2',
    receiverBankId: 'bank13',
  },
  {
    id: 'tx24',
    $id: 'txid24',
    name: 'Pharmacy',
    paymentChannel: 'in-store',
    accountId: 'acc3',
    amount: 32.5,
    pending: true,
    status: 'Processing',
    category: 'Food',
    date: '2024-06-24',
    image: 'https://example.com/images/tx24.jpg',
    type: 'Debit',
    $createdAt: '2024-06-24T11:20:00Z',
    channel: 'In-Store',
    senderBankId: 'bank3',
    receiverBankId: 'bank14',
  },
  {
    id: 'tx25',
    $id: 'txid25',
    name: 'Movie Theater',
    paymentChannel: 'in-store',
    accountId: 'acc1',
    amount: 25.0,
    pending: false,
    status: 'Success',
    category: 'Investment',
    date: '2024-06-25',
    image: 'https://example.com/images/tx25.jpg',
    type: 'Debit',
    $createdAt: '2024-06-25T20:00:00Z',
    channel: 'In-Store',
    senderBankId: 'bank1',
    receiverBankId: 'bank15',
  },
  {
    id: 'tx26',
    $id: 'txid26',
    name: 'Salary Deposit',
    paymentChannel: 'online',
    accountId: 'acc1',
    amount: 3000.0,
    pending: false,
    status: 'Success',
    category: 'Salary',
    date: '2024-06-26',
    image: 'https://example.com/images/tx26.jpg',
    type: 'Credit',
    $createdAt: '2024-06-26T09:00:00Z',
    channel: 'Online',
    senderBankId: 'bank16',
    receiverBankId: 'bank1',
  },
  {
    id: 'tx27',
    $id: 'txid27',
    name: 'Rent Payment',
    paymentChannel: 'online',
    accountId: 'acc2',
    amount: 1200.0,
    pending: false,
    status: 'Success',
    category: 'Housing',
    date: '2024-06-27',
    image: 'https://example.com/images/tx27.jpg',
    type: 'Debit',
    $createdAt: '2024-06-27T10:00:00Z',
    channel: 'Online',
    senderBankId: 'bank2',
    receiverBankId: 'bank17',
  },
  {
    id: 'tx28',
    $id: 'txid28',
    name: 'Gym Membership',
    paymentChannel: 'online',
    accountId: 'acc3',
    amount: 50.0,
    pending: false,
    status: 'Success',
    category: 'Subscription',
    date: '2024-06-28',
    image: 'https://example.com/images/tx28.jpg',
    type: 'Debit',
    $createdAt: '2024-06-28T14:30:00Z',
    channel: 'Online',
    senderBankId: 'bank3',
    receiverBankId: 'bank18',
  },
  {
    id: 'tx29',
    $id: 'txid29',
    name: 'Clothing Store',
    paymentChannel: 'in-store',
    accountId: 'acc1',
    amount: 89.99,
    pending: false,
    status: 'Success',
    category: 'Shopping',
    date: '2024-06-29',
    image: 'https://example.com/images/tx29.jpg',
    type: 'Debit',
    $createdAt: '2024-06-29T16:45:00Z',
    channel: 'In-Store',
    senderBankId: 'bank1',
    receiverBankId: 'bank19',
  },
  {
    id: 'tx30',
    $id: 'txid30',
    name: 'Dividend Payment',
    paymentChannel: 'online',
    accountId: 'acc2',
    amount: 75.5,
    pending: false,
    status: 'Success',
    category: 'Investment',
    date: '2024-06-30',
    image: 'https://example.com/images/tx30.jpg',
    type: 'Credit',
    $createdAt: '2024-06-30T09:00:00Z',
    channel: 'Online',
    senderBankId: 'bank20',
    receiverBankId: 'bank2',
  },
  {
    id: 'tx31',
    $id: 'txid31',
    name: 'Restaurant Dinner',
    paymentChannel: 'in-store',
    accountId: 'acc3',
    amount: 78.5,
    pending: false,
    status: 'Success',
    category: 'Food and Drink',
    date: '2024-07-01',
    image: 'https://example.com/images/tx31.jpg',
    type: 'Debit',
    $createdAt: '2024-07-01T20:30:00Z',
    channel: 'In-Store',
    senderBankId: 'bank3',
    receiverBankId: 'bank21',
  },
  {
    id: 'tx32',
    $id: 'txid32',
    name: 'Mobile Phone Bill',
    paymentChannel: 'online',
    accountId: 'acc1',
    amount: 65.0,
    pending: false,
    status: 'Success',
    category: 'Utilities',
    date: '2024-07-02',
    image: 'https://example.com/images/tx32.jpg',
    type: 'Debit',
    $createdAt: '2024-07-02T10:15:00Z',
    channel: 'Online',
    senderBankId: 'bank1',
    receiverBankId: 'bank22',
  },
  {
    id: 'tx33',
    $id: 'txid33',
    name: 'Book Store',
    paymentChannel: 'in-store',
    accountId: 'acc2',
    amount: 42.99,
    pending: false,
    status: 'Success',
    category: 'Loan',
    date: '2024-07-03',
    image: 'https://example.com/images/tx33.jpg',
    type: 'Debit',
    $createdAt: '2024-07-03T14:45:00Z',
    channel: 'In-Store',
    senderBankId: 'bank2',
    receiverBankId: 'bank23',
  },
  {
    id: 'tx34',
    $id: 'txid34',
    name: 'Car Insurance',
    paymentChannel: 'online',
    accountId: 'acc3',
    amount: 120.0,
    pending: false,
    status: 'Success',
    category: 'Income',
    date: '2024-07-04',
    image: 'https://example.com/images/tx34.jpg',
    type: 'Debit',
    $createdAt: '2024-07-04T09:30:00Z',
    channel: 'Online',
    senderBankId: 'bank3',
    receiverBankId: 'bank24',
  },
  {
    id: 'tx35',
    $id: 'txid35',
    name: 'Coffee Shop',
    paymentChannel: 'in-store',
    accountId: 'acc1',
    amount: 5.75,
    pending: false,
    status: 'Success',
    category: 'Food and Drink',
    date: '2024-07-05',
    image: 'https://example.com/images/tx35.jpg',
    type: 'Debit',
    $createdAt: '2024-07-05T08:20:00Z',
    channel: 'In-Store',
    senderBankId: 'bank1',
    receiverBankId: 'bank25',
  },
  {
    id: 'tx36',
    $id: 'txid36',
    name: 'Freelance Payment',
    paymentChannel: 'online',
    accountId: 'acc2',
    amount: 500.0,
    pending: false,
    status: 'Success',
    category: 'Income',
    date: '2024-07-06',
    image: 'https://example.com/images/tx36.jpg',
    type: 'Credit',
    $createdAt: '2024-07-06T15:00:00Z',
    channel: 'Online',
    senderBankId: 'bank26',
    receiverBankId: 'bank2',
  },
  {
    id: 'tx37',
    $id: 'txid37',
    name: 'Grocery Delivery',
    paymentChannel: 'online',
    accountId: 'acc3',
    amount: 95.5,
    pending: false,
    status: 'Success',
    category: 'Groceries',
    date: '2024-07-07',
    image: 'https://example.com/images/tx37.jpg',
    type: 'Debit',
    $createdAt: '2024-07-07T18:30:00Z',
    channel: 'Online',
    senderBankId: 'bank3',
    receiverBankId: 'bank27',
  },
  {
    id: 'tx38',
    $id: 'txid38',
    name: 'Streaming Service',
    paymentChannel: 'online',
    accountId: 'acc1',
    amount: 14.99,
    pending: false,
    status: 'Success',
    category: 'Investment',
    date: '2024-07-08',
    image: 'https://example.com/images/tx38.jpg',
    type: 'Debit',
    $createdAt: '2024-07-08T00:01:00Z',
    channel: 'Online',
    senderBankId: 'bank1',
    receiverBankId: 'bank28',
  },
  {
    id: 'tx39',
    $id: 'txid39',
    name: 'Public Transport',
    paymentChannel: 'in-store',
    accountId: 'acc2',
    amount: 30.0,
    pending: false,
    status: 'Success',
    category: 'Travel',
    date: '2024-07-09',
    image: 'https://example.com/images/tx39.jpg',
    type: 'Debit',
    $createdAt: '2024-07-09T07:45:00Z',
    channel: 'In-Store',
    senderBankId: 'bank2',
    receiverBankId: 'bank29',
  },
  {
    id: 'tx40',
    $id: 'txid40',
    name: 'Dentist Appointment',
    paymentChannel: 'in-store',
    accountId: 'acc3',
    amount: 150.0,
    pending: true,
    status: 'Processing',
    category: 'Housing',
    date: '2024-07-10',
    image: 'https://example.com/images/tx40.jpg',
    type: 'Debit',
    $createdAt: '2024-07-10T14:00:00Z',
    channel: 'In-Store',
    senderBankId: 'bank3',
    receiverBankId: 'bank30',
  },
  {
    id: 'tx41',
    $id: 'txid41',
    name: 'Online Shopping',
    paymentChannel: 'online',
    accountId: 'acc1',
    amount: 79.99,
    pending: false,
    status: 'Processing',
    category: 'Shopping',
    date: '2024-07-11',
    image: 'https://example.com/images/tx41.jpg',
    type: 'Debit',
    $createdAt: '2024-07-11T21:30:00Z',
    channel: 'Online',
    senderBankId: 'bank1',
    receiverBankId: 'bank31',
  },
  {
    id: 'tx42',
    $id: 'txid42',
    name: 'Electric Bill',
    paymentChannel: 'online',
    accountId: 'acc2',
    amount: 85.5,
    pending: false,
    status: 'Success',
    category: 'Utilities',
    date: '2024-07-12',
    image: 'https://example.com/images/tx42.jpg',
    type: 'Debit',
    $createdAt: '2024-07-12T14:30:00Z',
    channel: 'Online',
    senderBankId: 'bank2',
    receiverBankId: 'bank22',
  },
  {
    id: 'tx43',
    $id: 'txid43',
    name: 'Freelance Payment',
    paymentChannel: 'online',
    accountId: 'acc1',
    amount: 750.0,
    pending: false,
    status: 'Success',
    category: 'Income',
    date: '2024-07-13',
    image: 'https://example.com/images/tx43.jpg',
    type: 'Credit',
    $createdAt: '2024-07-13T10:15:00Z',
    channel: 'Online',
    senderBankId: 'bank23',
    receiverBankId: 'bank1',
  },
  {
    id: 'tx44',
    $id: 'txid44',
    name: 'Car Insurance',
    paymentChannel: 'online',
    accountId: 'acc3',
    amount: 120.75,
    pending: false,
    status: 'Success',
    category: 'Interest',
    date: '2024-07-14',
    image: 'https://example.com/images/tx44.jpg',
    type: 'Debit',
    $createdAt: '2024-07-14T09:00:00Z',
    channel: 'Online',
    senderBankId: 'bank3',
    receiverBankId: 'bank24',
  },
  {
    id: 'tx45',
    $id: 'txid45',
    name: 'Bookstore Purchase',
    paymentChannel: 'in-store',
    accountId: 'acc2',
    amount: 42.99,
    pending: false,
    status: 'Success',
    category: 'Shopping',
    date: '2024-07-15',
    image: 'https://example.com/images/tx45.jpg',
    type: 'Debit',
    $createdAt: '2024-07-15T16:45:00Z',
    channel: 'In-Store',
    senderBankId: 'bank2',
    receiverBankId: 'bank25',
  },
  {
    id: 'tx46',
    $id: 'txid46',
    name: 'ATM Withdrawal',
    paymentChannel: 'atm',
    accountId: 'acc1',
    amount: 100.0,
    pending: false,
    status: 'Success',
    category: 'Withdrawal',
    date: '2024-07-16',
    image: 'https://example.com/images/tx46.jpg',
    type: 'Debit',
    $createdAt: '2024-07-16T13:30:00Z',
    channel: 'ATM',
    senderBankId: 'bank1',
    receiverBankId: 'bank1',
  },
  {
    id: 'tx47',
    $id: 'txid47',
    name: 'Streaming Service',
    paymentChannel: 'online',
    accountId: 'acc3',
    amount: 14.99,
    pending: false,
    status: 'Success',
    category: 'Investment',
    date: '2024-07-17',
    image: 'https://example.com/images/tx47.jpg',
    type: 'Debit',
    $createdAt: '2024-07-17T20:00:00Z',
    channel: 'Online',
    senderBankId: 'bank3',
    receiverBankId: 'bank26',
  },
  {
    id: 'tx48',
    $id: 'txid48',
    name: 'Gardening Supplies',
    paymentChannel: 'in-store',
    accountId: 'acc2',
    amount: 67.25,
    pending: false,
    status: 'Success',
    category: 'Housing',
    date: '2024-07-18',
    image: 'https://example.com/images/tx48.jpg',
    type: 'Debit',
    $createdAt: '2024-07-18T11:15:00Z',
    channel: 'In-Store',
    senderBankId: 'bank2',
    receiverBankId: 'bank27',
  },
  {
    id: 'tx49',
    $id: 'txid49',
    name: 'Public Transport Pass',
    paymentChannel: 'online',
    accountId: 'acc1',
    amount: 75.0,
    pending: false,
    status: 'Success',
    category: 'Travel',
    date: '2024-07-19',
    image: 'https://example.com/images/tx49.jpg',
    type: 'Debit',
    $createdAt: '2024-07-19T08:45:00Z',
    channel: 'Online',
    senderBankId: 'bank1',
    receiverBankId: 'bank28',
  },
  {
    id: 'tx50',
    $id: 'txid50',
    name: 'Dental Checkup',
    paymentChannel: 'in-store',
    accountId: 'acc3',
    amount: 150.0,
    pending: true,
    status: 'Processing',
    category: 'Credit Card',
    date: '2024-07-20',
    image: 'https://example.com/images/tx50.jpg',
    type: 'Debit',
    $createdAt: '2024-07-20T14:00:00Z',
    channel: 'In-Store',
    senderBankId: 'bank3',
    receiverBankId: 'bank29',
  },
  {
    id: 'tx51',
    $id: 'txid51',
    name: 'Pet Supplies',
    paymentChannel: 'online',
    accountId: 'acc2',
    amount: 55.99,
    pending: false,
    status: 'Success',
    category: 'Payment',
    date: '2024-07-21',
    image: 'https://example.com/images/tx51.jpg',
    type: 'Debit',
    $createdAt: '2024-07-21T17:30:00Z',
    channel: 'Online',
    senderBankId: 'bank2',
    receiverBankId: 'bank30',
  },
  {
    id: 'tx52',
    $id: 'txid52',
    name: 'Music Festival Tickets',
    paymentChannel: 'online',
    accountId: 'acc1',
    amount: 180.0,
    pending: false,
    status: 'Success',
    category: 'Shopping',
    date: '2024-07-22',
    image: 'https://example.com/images/tx52.jpg',
    type: 'Debit',
    $createdAt: '2024-07-22T19:45:00Z',
    channel: 'Online',
    senderBankId: 'bank1',
    receiverBankId: 'bank31',
  },
  {
    id: 'tx53',
    $id: 'txid53',
    name: 'Laptop Repair',
    paymentChannel: 'in-store',
    accountId: 'acc3',
    amount: 220.0,
    pending: false,
    status: 'Success',
    category: 'Other',
    date: '2024-07-23',
    image: 'https://example.com/images/tx53.jpg',
    type: 'Debit',
    $createdAt: '2024-07-23T13:15:00Z',
    channel: 'In-Store',
    senderBankId: 'bank3',
    receiverBankId: 'bank32',
  },
  {
    id: 'tx54',
    $id: 'txid54',
    name: 'Dividend Payment',
    paymentChannel: 'online',
    accountId: 'acc2',
    amount: 65.25,
    pending: false,
    status: 'Success',
    category: 'Investment',
    date: '2024-07-24',
    image: 'https://example.com/images/tx54.jpg',
    type: 'Credit',
    $createdAt: '2024-07-24T09:30:00Z',
    channel: 'Online',
    senderBankId: 'bank33',
    receiverBankId: 'bank2',
  },
  {
    id: 'tx55',
    $id: 'txid55',
    name: 'Parking Fee',
    paymentChannel: 'in-store',
    accountId: 'acc1',
    amount: 15.0,
    pending: false,
    status: 'Success',
    category: 'Subscription',
    date: '2024-07-25',
    image: 'https://example.com/images/tx55.jpg',
    type: 'Debit',
    $createdAt: '2024-07-25T11:00:00Z',
    channel: 'In-Store',
    senderBankId: 'bank1',
    receiverBankId: 'bank34',
  },
  {
    id: 'tx56',
    $id: 'txid56',
    name: 'Gym Membership',
    paymentChannel: 'online',
    accountId: 'acc3',
    amount: 49.99,
    pending: false,
    status: 'Success',
    category: 'Salary',
    date: '2024-07-26',
    image: 'https://example.com/images/tx56.jpg',
    type: 'Debit',
    $createdAt: '2024-07-26T08:00:00Z',
    channel: 'Online',
    senderBankId: 'bank3',
    receiverBankId: 'bank35',
  },
  {
    id: 'tx57',
    $id: 'txid57',
    name: 'Smartphone Purchase',
    paymentChannel: 'online',
    accountId: 'acc2',
    amount: 799.99,
    pending: false,
    status: 'Processing',
    category: 'Rent',
    date: '2024-07-27',
    image: 'https://example.com/images/tx57.jpg',
    type: 'Debit',
    $createdAt: '2024-07-27T15:30:00Z',
    channel: 'Online',
    senderBankId: 'bank2',
    receiverBankId: 'bank36',
  },
  {
    id: 'tx58',
    $id: 'txid58',
    name: 'Grocery Delivery',
    paymentChannel: 'online',
    accountId: 'acc1',
    amount: 95.5,
    pending: false,
    status: 'Success',
    category: 'Groceries',
    date: '2024-07-28',
    image: 'https://example.com/images/tx58.jpg',
    type: 'Debit',
    $createdAt: '2024-07-28T18:45:00Z',
    channel: 'Online',
    senderBankId: 'bank1',
    receiverBankId: 'bank37',
  },
  {
    id: 'tx59',
    $id: 'txid59',
    name: 'Home Insurance',
    paymentChannel: 'online',
    accountId: 'acc3',
    amount: 135.0,
    pending: false,
    status: 'Success',
    category: 'Interest',
    date: '2024-07-29',
    image: 'https://example.com/images/tx59.jpg',
    type: 'Debit',
    $createdAt: '2024-07-29T10:00:00Z',
    channel: 'Online',
    senderBankId: 'bank3',
    receiverBankId: 'bank38',
  },
  {
    id: 'tx60',
    $id: 'txid60',
    name: 'Charitable Donation',
    paymentChannel: 'online',
    accountId: 'acc2',
    amount: 100.0,
    pending: false,
    status: 'Success',
    category: 'Deposit',
    date: '2024-07-30',
    image: 'https://example.com/images/tx60.jpg',
    type: 'Debit',
    $createdAt: '2024-07-30T15:00:00Z',
    channel: 'Online',
    senderBankId: 'bank2',
    receiverBankId: 'bank39',
  },
];
const CREDITCARDS: TCreditCard[] = [
  {
    bankId: 'bank1',
    bank: 'Example Bank',
    name: 'Platinum Rewards Card',
    number: '**** **** **** 1234',
    expiry: '06/25',
    color: 'blue',
  },
  {
    bankId: 'bank2',
    bank: 'Another Bank',
    name: 'Gold Card',
    number: '**** **** **** 5678',
    expiry: '09/24',
    color: 'green',
  },
  {
    bankId: 'bank3',
    bank: 'Sample Credit Union',
    name: 'Silver Card',
    number: '**** **** **** 9012',
    expiry: '12/23',
    color: 'purple',
  },
  {
    bankId: 'bank4',
    bank: 'Credit Bank',
    name: 'Cashback Card',
    number: '**** **** **** 3456',
    expiry: '03/27',
    color: 'red',
  },
  {
    bankId: 'bank5',
    bank: 'Card Provider Inc.',
    name: 'Travel Card',
    number: '**** **** **** 7890',
    expiry: '02/26',
    color: 'teal',
  },
  {
    bankId: 'bank6',
    bank: 'National Bank',
    name: 'Student Card',
    number: '**** **** **** 2345',
    expiry: '11/25',
    color: 'yellow',
  },
  {
    bankId: 'bank7',
    bank: 'Finance Group',
    name: 'Business Card',
    number: '**** **** **** 6789',
    expiry: '08/28',
    color: 'indigo',
  },
  {
    bankId: 'bank8',
    bank: 'Digital Bank',
    name: 'Virtual Card',
    number: '**** **** **** 0123',
    expiry: '04/30',
    color: 'pink',
  },
  {
    bankId: 'bank9',
    bank: 'Online Banking',
    name: 'Secure Card',
    number: '**** **** **** 4567',
    expiry: '07/29',
    color: 'cyan',
  },
  {
    bankId: 'bank10',
    bank: 'Credit Services',
    name: 'Rewards Plus Card',
    number: '**** **** **** 8901',
    expiry: '10/31',
    color: 'gray',
  },
];
export { USER, ACCOUNTS, BANKS, TRANSACTIONS, CREDITCARDS };
